export const jobs = [
  {
    id: 1,
    company: "Magnet Forensics",
    startDate: "May 2017",
    endDate: "Present",
    logo: "/images/magnet-forensics.jpg",
    details: [
      "Developed several products with React and the new React Hooks API",
      "Designed a strategy for gradually refactoring legacy AngularJS code to React",
      "Provisioned AWS applications using Serverless Framework for easy deployment",
      "Created AWS Lambda functions that automatically manages EC2 instances to reduce costs",
      "Architected a new GoLang API to replace an exisiting Python 2 API",
      "Used Git and Gerrit for source control and code reviews",
      "Mentored coop students to help minimize ramp up time with new products and processes",
      "Hosted lunch and learns for the whole company on technologies such as React, Storybook, and Serverless Framework",
      "Wrote unit, functional, and end-to-end tests in parallel with features",
      "Worked on a team that developed applications using the C# MVVM software design pattern",
      "Used database migrations to make changes to database schemas that were already being used in production",
    ],
    skills: [
      "JavaScript",
      "Python",
      "GoLang",
      "C#",
      "C++",
      "React",
      "React Hooks",
      "Redux",
      "Jest",
      "Storybook",
      "Webpack",
      "Express",
      "Protobuf",
      "Git",
      "Serverless Framework",
      "Docker",
      "SQLite",
      "MySQL",
      "PostgreSQL",
      "Clojure",
      "AWS S3",
      "AWS EC2",
      "AWS Cognito",
      "AWS DynamoDB",
      "AWS Cloudfront",
      "Semanic UI",
      "Bootstrap",
      "Elasticsearch",
      "Gerrit",
      "Jenkins",
      "XAML",
      "D3.js",
      "Selenium",
      "Scrum",
      "Kanban",
    ],
  },
  {
    id: 2,
    company: "IBM",
    startDate: "May 2015",
    endDate: "August 2016",
    logo: "/images/ibm.jpg",
    details: [
      "Designed and maintained Selenium page objects for end to end testing",
      "Architectured and implemented front end features using JavaScript and Dojo Toolkit",
      "Debugged and fixed defects in the product",
      "Worked on a team that followed Agile practices",
      "Was a member of the IBM Future Blue Executive team",
    ],
    skills: [
      "JavaScript",
      "HTML",
      "CSS",
      "JUnit",
      "Selenium",
      "Dojo Toolkit",
      "Java",
      "RESTful APIs",
      "NodeJS",
      "Semanic UI",
      "PostgreSQL",
    ],
  },
  {
    id: 3,
    company: "Huron Geomatics",
    startDate: "June 2011",
    endDate: "August 2014",
    logo: "/images/huron-geomatics.jpg",
    details: [
      "Designed and developed the company website using Wordpress",
      "Created several applications for local businesses using C# and Microsoft SQL Server",
      "Developed internal tools for collegues to use",
    ],
    skills: [
      "C#",
      "Wordpress",
      "PHP",
      "D3.js",
      "Microsoft SQL Server",
      "JavaScript",
      "HTML",
      "CSS",
    ],
  },
]
